{
 "title": "Kafka metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_memory_max_bytes", "legendFormat": "__auto" }
   ]
  },
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Bytes PerSec - test_topic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_BrokerTopicMetrics_BytesInPerSec_topic_test_topic_",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bytest PerSec - test_topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_BrokerTopicMetrics_BytesInPerSec_topic_test_topic_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bytes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_BrokerTopicMetrics_BytesInPerSec_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS - test_topic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_BrokerTopicMetrics_TotalProduceRequestsPerSec_topic_test_topic_",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total messages - test_topic",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_BrokerTopicMetrics_MessagesInPerSec_topic_test_topic_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total messages",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_BrokerTopicMetrics_MessagesInPerSec_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed fetch RPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_BrokerTopicMetrics_FailedFetchRequestsPerSec_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total failed requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_BrokerTopicMetrics_FailedFetchRequestsPerSec_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitions count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_ReplicaManager_PartitionCount_",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_ReplicaManager_UnderReplicatedPartitions_",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}